xis = input('Digite algo ')
print('O tipo primitivo de x é:', type(xis))
print('Maiúscula?', xis.isupper())
print('Numérico?', xis.isnumeric())
print('Imprimível?', xis.isprintable())
print('Minúscula?', xis.islower())
print('É espaço?', xis.isspace())
print('É letra?', xis.isalpha())
print('É CAPTALIZADA?', xis.istitle())